apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jill-pill
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - thejillpill.com
      secretName: jill-pill-tls
  rules:
    - host: thejillpill.com
      http:
        paths:
          - backend:
              serviceName: jill-pill
              servicePort: 80
